general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = hyprctl dispatch dpms on     # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on && loginctl lock-session # to avoid having to press a key twice to turn on the display.
} # avoid starting multiple hyprlock instances.
#    before_sleep_cmd = loginctl lock-session

listener {
    timeout = 150                                # 2.5min.
    on-timeout = brightnessctl -s set 10 & if [[ $(brightnessctl -d asus::screenpad g) > 10 ]]; then brightnessctl -sd asus::screenpad s 10; else brightnessctl -sd asus::screenpad; fi         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r & brightnessctl -rd asus::screenpad                # monitor backlight restore.
}

# turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
listener {
    timeout = 10                                        # 2.5min.
    on-timeout = brightnessctl -sd asus::kbd_backlight set 0 # && echo $(powerprofilesctl get) > ~/Scripts/powerprofile && powerprofilesctl set power-saver# turn off keyboard backlight.
    on-resume = brightnessctl -rd asus::kbd_backlight # & powerprofilesctl set $(cat ~/Scripts/powerprofile)       # turn on keyboard backlight.
    ignore_inhibit=true
}

listener {
    timeout = 185                                 # 5min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout = 180                                                     # 5.5min
    on-timeout = hyprctl dispatch dpms off & brightnessctl -d asus::screenpad s 0                           # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && brightnessctl -r && brightnessctl -rd asus::screenpad          # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 900                                # 30min
    on-timeout = systemctl hibernate                # suspend pc
}
